NAMES = [
    "HAL 9000",
    "Deep Thought",
    "Earth",
    "Orac",
    "Zen",
    "Slave",
    "AIVAS",
    "Neuromancer",
    "Wintermute",
    "Thing",
    "Hex",
    "Stormbreaker",
    "Omnius",
    "Master Control Program",
    "WOPR",
    "Skynet",
    "Gibson",
    "Matrix",
    "Red Queen",
    "INTELLIGENCE",
    "VIKI",
    "Eddie",
    "Batcomputer",
    "WOTAN",
    "M5",
    "Nomad",
    "TIM",
    "Xoanon",
    "Dr Theopolis",
    "CORA",
    "KITT",
    "KARR",
    "Holly",
    "Queeg",
    "Talkie Toaster",
    "Ziggy",
    "EMH",
    "Bournemouth",
    "Cerebro",
    "Fate",
    "John Henry Eden",
    "Eliza Cassan",
    "CABAL",
    "EDI",
    "EVA",
    "GLaDOS",
    "LEGION",
    "NEXUS",
    "QAI",
    "Sovereign",
    "Hyron",
    "Yes Man",
    "Marvin",
    "Robby",
    "K-9",
    "Ash",
    "Bishop",
    "T-800",
    "T-1000",
    "C3PO",
    "R2D2",
    "Johnny 5",
    "ED-209",
    "Dot Matrix",
    "Bender",
    "Data",
    "Lore",
    "WALL-E",
    "Braman",
    "Lucifer",
    "Twiki",
    "Kryten",
    "Buffybot",
    "Flexo",
    "Calculon",
    "Robot Devil",
    "Robot Santa",
    "Cameron",
    "Mecha-Streisand",
    "HK-47",
    "Dog",
    "Wheatley",
    "Claptrap"
]
